services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8501:8501"
      - "8888:8888"
    environment:
      - DATABASE_URL=postgresql://agent_user:agent_pass@postgres:5432/react_agent_db
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      # Gemini Configuration
      - GEMINI_MODEL_NAME=${GEMINI_MODEL_NAME}
      - GEMINI_TEMPERATURE=${GEMINI_TEMPERATURE}
      - GEMINI_MAX_TOKENS=${GEMINI_MAX_TOKENS}
      - GEMINI_TOP_P=${GEMINI_TOP_P}
      - GEMINI_TOP_K=${GEMINI_TOP_K}
      # LangGraph Configuration
      - LANGGRAPH_CHECKPOINTER_TYPE=${LANGGRAPH_CHECKPOINTER_TYPE}
      - LANGGRAPH_MAX_CONCURRENT_SESSIONS=${LANGGRAPH_MAX_CONCURRENT_SESSIONS}
      - LANGGRAPH_SESSION_TIMEOUT_MINUTES=${LANGGRAPH_SESSION_TIMEOUT_MINUTES}
      - MAX_CONVERSATION_TURNS=${MAX_CONVERSATION_TURNS:-50}
      - AGENT_MAX_ITERATIONS=${AGENT_MAX_ITERATIONS:-10}
      # BigTool Configuration
      - BIGTOOL_ENABLED=${BIGTOOL_ENABLED}
      - BIGTOOL_MAX_TOOLS=${BIGTOOL_MAX_TOOLS}
      - BIGTOOL_SIMILARITY_THRESHOLD=${BIGTOOL_SIMILARITY_THRESHOLD}
      - BIGTOOL_INDEX_BATCH_SIZE=${BIGTOOL_INDEX_BATCH_SIZE}
      - BIGTOOL_SEARCH_LIMIT=${BIGTOOL_SEARCH_LIMIT}
      - BIGTOOL_VECTOR_STORE=${BIGTOOL_VECTOR_STORE:-in_memory}
      - TOOL_SEARCH_TOP_K=${TOOL_SEARCH_TOP_K:-3}
      - MEMORY_STORE_SIZE=${MEMORY_STORE_SIZE:-1000}
      # Cache Configuration
      - CALCULATION_CACHE_TTL_HOURS=${CALCULATION_CACHE_TTL_HOURS}
      - CONVERSATION_HISTORY_LIMIT=${CONVERSATION_HISTORY_LIMIT}
      # Redis Configuration
      - REDIS_URL=${REDIS_URL}
      # Debug Configuration
      - DEBUG=${DEBUG}
      - LOG_LEVEL=${LOG_LEVEL}
    depends_on:
      - postgres
    volumes:
      - ./app:/app/app
      - ./notebooks:/app/notebooks
      - ./tests:/app/tests

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=agent_user
      - POSTGRES_PASSWORD=agent_pass
      - POSTGRES_DB=react_agent_db
    ports:
      - "5432:5432"
    volumes:
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
